"""Parser for the Montgomery County Case Information Sheet PDF.

The CIS is a small (~3KB) text-extractable PDF auto-generated by the
e-filing system for every civil case. It's the canonical source of:

  - PRAYER AMOUNT  (exact $$ the plaintiff is demanding)
  - PARCEL NUMBER  (canonical, matches Summary tab)
  - ACTION TYPE    (e.g., "MORTGAGE FORECLOSURE")
  - CASE TYPE      (e.g., "Civil")
  - JURY DEMAND    (Yes/No)
  - Main plaintiff + defendant
  - Filing attorney

Format (observed in case 2026 CV 03024):

    Filer: Austin B Barnes
    PARTICIPANT NAME TYPE ATTORNEY FOR PARTY
    TAX EASE OH V LLC MAIN PLAINTIFF BARNES
    THOMAS SCOTT DAVIS MAIN DEFENDANT
    CATEGORY VALUE
    CASE TYPE Civil
    JURY DEMAND No
    PRAYER AMOUNT 7328.43
    ACTION TYPE MORTGAGE FORECLOSURE
    TYPE OF RESOLUTION
    PARCEL NUMBER (MORTGAGE FORECLOSURE ONLY) R72048030115
"""
from __future__ import annotations

import re
from dataclasses import dataclass

import pypdfium2 as pdfium


@dataclass
class CaseInfoSheet:
    prayer_amount: float | None = None
    parcel_number: str = ""
    action_type: str = ""
    case_type: str = ""
    jury_demand: str = ""           # "Yes" | "No" | ""
    main_plaintiff: str = ""
    main_defendant: str = ""
    filer_attorney: str = ""
    raw_text: str = ""


def _extract_text(pdf_bytes: bytes) -> str:
    """Pull text from a PDF blob using pypdfium2."""
    pdf = pdfium.PdfDocument(pdf_bytes)
    parts: list[str] = []
    for page in pdf:
        parts.append(page.get_textpage().get_text_range())
    return "\n".join(parts)


_FILER_RE = re.compile(r"Filer:\s*(.+?)(?:\n|$)", re.I)
_PRAYER_RE = re.compile(r"PRAYER\s+AMOUNT\s+([\d,]+\.?\d*)", re.I)
_PARCEL_RE = re.compile(
    r"PARCEL\s+NUMBER\s*(?:\([^)]*\))?\s+([A-Z0-9 ]+?)(?:\n|$|\s{2,}|CASE NUMBER)",
    re.I,
)
_ACTION_RE = re.compile(r"ACTION\s+TYPE\s+(.+?)(?:\n|$)", re.I)
_CASE_TYPE_RE = re.compile(r"CASE\s+TYPE\s+(.+?)(?:\n|$)", re.I)
_JURY_RE = re.compile(r"JURY\s+DEMAND\s+(.+?)(?:\n|$)", re.I)


def parse_cis(pdf_bytes: bytes) -> CaseInfoSheet:
    """Parse a Case Information Sheet PDF blob into structured fields."""
    text = _extract_text(pdf_bytes)
    cis = CaseInfoSheet(raw_text=text)

    if m := _FILER_RE.search(text):
        cis.filer_attorney = m.group(1).strip()
    if m := _PRAYER_RE.search(text):
        try:
            cis.prayer_amount = float(m.group(1).replace(",", ""))
        except ValueError:
            pass
    if m := _PARCEL_RE.search(text):
        cis.parcel_number = m.group(1).strip().replace(" ", "")
    if m := _ACTION_RE.search(text):
        cis.action_type = m.group(1).strip()
    if m := _CASE_TYPE_RE.search(text):
        cis.case_type = m.group(1).strip()
    if m := _JURY_RE.search(text):
        cis.jury_demand = m.group(1).strip()

    # Main plaintiff + defendant — the format is fixed-position after the
    # "PARTICIPANT NAME TYPE ATTORNEY FOR PARTY" header. We look for rows
    # where the line ends in "PLAINTIFF" or "DEFENDANT" and grab the prefix.
    plaintiff_match = re.search(r"^(.+?)\s+MAIN\s+PLAINTIFF\b", text, re.M | re.I)
    defendant_match = re.search(r"^(.+?)\s+MAIN\s+DEFENDANT\b", text, re.M | re.I)
    if plaintiff_match:
        cis.main_plaintiff = plaintiff_match.group(1).strip()
    if defendant_match:
        cis.main_defendant = defendant_match.group(1).strip()

    return cis


if __name__ == "__main__":
    import sys
    from pathlib import Path

    if len(sys.argv) < 2:
        # Default: use the sample we downloaded for case 03024
        path = (Path(__file__).resolve().parents[1] / "output" /
                "phase_b_run_4" / "cis_raw")
    else:
        path = Path(sys.argv[1])

    cis = parse_cis(path.read_bytes())
    print(f"=== Parsed {path.name} ===")
    print(f"  prayer_amount  : {cis.prayer_amount}")
    print(f"  parcel_number  : {cis.parcel_number!r}")
    print(f"  action_type    : {cis.action_type!r}")
    print(f"  case_type      : {cis.case_type!r}")
    print(f"  jury_demand    : {cis.jury_demand!r}")
    print(f"  main_plaintiff : {cis.main_plaintiff!r}")
    print(f"  main_defendant : {cis.main_defendant!r}")
    print(f"  filer_attorney : {cis.filer_attorney!r}")
